### PR TITLE
Update to python3 as MacOS12.3 removes 2.x

### LINKED ISSUE #21: MacOS Monterey 12.3 breaks the workflow
I've raised PR #20 which tries to make it work again, but haven't had time to do very thorough checking.
Hope it will help you fix the compatibility faster anyway :)

### PR DESCRIPTION
**Pull request by denisbr**
Apple removed Python2 from MacOS Monterey 12.3
This commit makes the bluetooth workflow work in 12.3
No backwards compatibility checked, so might break on older OS

### CODE REVIEW

**Comment by vegardinho** [comment]
I do value backwards compatibility, so any help here is appreciated. (@deanishe?)

**Comment by abosnjakovic** [comment]
From my understanding there is no backward support from 3 to 2 so I guess the new releases will support 3 only? If that's not acceptable, looking at maintaining 2 versions could be simpler than creating a system or process around supporting multiple python versions and each release would have a build for both in that case. If that is acceptable we can just tag v2 and v3 and move on keeping in mind that v2 has an ending support life?

**Comment by vegardinho** [comment]
Sounds reasonable to me. What would be the best way of doing separate versions? Forking a new v3 repository, and support them separately?

**Comment by bumpux** [comment]
Would love to have this working on 12.3 🙏 -- do you need volunteers to test a new version with @denisbr 's commit?

**Comment by ghveem** [comment]
Tested on macOS Monterey 12.3. Macbook M1. Works, no errors.

**Comment by denisbr** [comment]
I've been using this since I opened the PR on an x86 MacBookPro macOS 12.3(.1), and haven't had any issues.

**Pull request merged**
